/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyfinalalgoritmos;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author melis
 */
public class frmProyecto extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private List<Proyecto> proyectos;
    private List<Persona> personas;
 
    String accion = "";
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    String fechaActual="";
    Proyecto proyectoEditable = null;
    public frmProyecto(Proyecto proyecto){
        initComponents();
        if(proyecto ==null){
            accion ="N";
            lblTitulo.setText("NUEVO PROYECTO");
        }else{
            accion ="E";
            lblTitulo.setText("EDITAR PROYECTO");
        }
        proyectos = GestionArchivos.leerProyectos();
        personas = GestionArchivos.leerPersonas();
        
        try {
            MaskFormatter dateFormatter = new MaskFormatter("##/##/####"); 
            dateFormatter.setPlaceholderCharacter('_');
            txtFechaCreacion.setColumns(10);
            txtFechaCreacion.setFormatterFactory(new DefaultFormatterFactory(dateFormatter));
            
            txtFechaInicio.setColumns(10);
            txtFechaInicio.setFormatterFactory(new DefaultFormatterFactory(dateFormatter));
            
            txtFechaFin.setColumns(10);
            txtFechaFin.setFormatterFactory(new DefaultFormatterFactory(dateFormatter));
        }catch (ParseException e) {
            e.printStackTrace();
        }
        
        
           // Obtener el modelo actual del comboBox
        DefaultComboBoxModel<Persona> model = new DefaultComboBoxModel<>();
        model.addElement(new Persona(-1, "","(Seleccione) -"));
        for (Persona persona : personas) {
            model.addElement(persona);
        }
        cboResponsable.setModel(model); 
        
        if(accion == "N"){
            chckActivo.setSelected(true);
            fechaActual = dateFormat.format(new Date()); 
            txtFechaCreacion.setText(fechaActual);
            txtFechaCreacion.setEnabled(false);
            cboEstado.setSelectedIndex(1);
            cboEstado.setEnabled(false);
        }else{
            proyectoEditable = proyecto;
            cboEstado.setEnabled(true);
            txtCodigo.setText(proyecto.getCodigo());
            txtNombre.setText(proyecto.getNombre());
            textAreaDescripcion.setText(proyecto.getDescripcion());
            txtFechaCreacion.setText(proyecto.getFechaCreacion());
            txtFechaCreacion.setEnabled(false);
            spinHorasEstimadas.setValue(proyecto.getHorasEstimadas());
            txtFechaInicio.setText(proyecto.getFechaInicio());
            txtFechaFin.setText(proyecto.getFechaFin());
            System.out.println(proyecto.getPorcAvance());
            sldAvance.setValue(proyecto.getPorcAvance());
            
            Persona responsable = new Persona();
            for(Persona p : personas){
                if(p.getId()==proyecto.getResponsableId()){
                    cboResponsable.setSelectedItem(p);
                }
            }

            cboEstado.setSelectedItem(proyecto.getEstado());  
            chckActivo.setSelected(proyecto.isActivo());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescripcion = new javax.swing.JTextArea();
        txtFechaCreacion = new javax.swing.JFormattedTextField();
        spinHorasEstimadas = new javax.swing.JSpinner();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        txtFechaFin = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        cboResponsable = new javax.swing.JComboBox<>();
        chckActivo = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        sldAvance = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText(" Proyecto");

        jLabel2.setText("Código:");

        jLabel3.setText("Descipción:");

        jLabel4.setText("Fecha Creación:");

        jLabel5.setText("Horas Estimado:");

        jLabel6.setText("Fecha Inicio:");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha Fin:");

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textAreaDescripcion.setColumns(10);
        textAreaDescripcion.setRows(3);
        textAreaDescripcion.setTabSize(4);
        jScrollPane1.setViewportView(textAreaDescripcion);

        txtFechaCreacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        txtFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioActionPerformed(evt);
            }
        });

        txtFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel8.setText("Responsable:");

        cboResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboResponsableActionPerformed(evt);
            }
        });

        chckActivo.setText("Activo");

        jLabel9.setText("Nombre:");

        jLabel10.setText("Estado:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Seleccione)", "No Iniciado", "En Proceso", "Finalizado" }));

        sldAvance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("% Avance:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chckActivo)
                                .addGap(25, 25, 25))
                            .addComponent(txtNombre)
                            .addComponent(txtCodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sldAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 41, Short.MAX_VALUE)))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinHorasEstimadas, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnGuardar)
                        .addGap(58, 58, 58)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinHorasEstimadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cboResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sldAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chckActivo)
                            .addComponent(jLabel10)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(jButton2)))
                    .addComponent(jLabel1))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(!formularioValido()){
            JOptionPane.showMessageDialog(this, "Hay problemas en los datos ingresados, verifique.");
        }else{
            if(accion=="N"){
                Proyecto proyectoNuevo = new Proyecto();
                if(proyectos==null){
                    this.proyectos = new ArrayList<>();
                    proyectoNuevo.setId(1);
                }else{
                    proyectoNuevo.setId(proyectos.get(proyectos.size()-1).getId()+1);
                }
                proyectoNuevo.setCodigo(txtCodigo.getText());
                proyectoNuevo.setNombre(txtNombre.getText());
                proyectoNuevo.setDescripcion(textAreaDescripcion.getText());
                //proyecto.setFechaCreacion(txtFechaCreacion.getText());
                proyectoNuevo.setHorasEstimadas(Integer.parseInt(spinHorasEstimadas.getValue().toString()));

                proyectoNuevo.setFechaCreacion(fechaActual);
                proyectoNuevo.setFechaInicio(txtFechaInicio.getText());
                proyectoNuevo.setFechaFin(txtFechaFin.getText());

                Persona personaSeleccionada = (Persona) cboResponsable.getSelectedItem();
                if (personaSeleccionada != null) {
                    int id = personaSeleccionada.getId();
                     proyectoNuevo.setResponsableId(id);
                }
                proyectoNuevo.setPorcAvance(0);
                proyectoNuevo.setEstado("No Iniciado");
                proyectoNuevo.setActivo(chckActivo.isSelected());
                proyectos.add(proyectoNuevo);
                GestionArchivos.guardarProyecto(proyectos);

                JOptionPane.showMessageDialog(this, "Proyecto añadido con éxito.");

                
            }else{// cuando accion ="E"
                Proyecto proyectoEditado = new Proyecto();
                if(proyectos==null){
                    this.proyectos = new ArrayList<>();
                    proyectoEditado.setId(1);
                }else{
                    proyectoEditado.setId(proyectoEditable.getId());
                }
                proyectoEditado.setCodigo(txtCodigo.getText());
                proyectoEditado.setNombre(txtNombre.getText());
                proyectoEditado.setDescripcion(textAreaDescripcion.getText());
                proyectoEditado.setHorasEstimadas(Integer.parseInt(spinHorasEstimadas.getValue().toString()));

                proyectoEditado.setFechaCreacion(proyectoEditable.getFechaCreacion());
                proyectoEditado.setFechaInicio(txtFechaInicio.getText());
                proyectoEditado.setFechaFin(txtFechaFin.getText());

                Persona personaSeleccionada = (Persona) cboResponsable.getSelectedItem();
                if (personaSeleccionada != null) {
                    int id = personaSeleccionada.getId();
                     proyectoEditado.setResponsableId(id);
                }
                proyectoEditado.setPorcAvance(sldAvance.getValue());
                proyectoEditado.setEstado(cboEstado.getSelectedItem().toString());
                proyectoEditado.setActivo(chckActivo.isSelected());
                for (int i = 0; i < proyectos.size(); i++) {
                    if (proyectos.get(i).getId() == proyectoEditado.getId()) {
                        proyectos.set(i, proyectoEditado);  // Reemplazamos
                        break;  // Salir del bucle una vez encontrado
                    }
                }
                        
                GestionArchivos.guardarProyecto(proyectos);

                JOptionPane.showMessageDialog(this, "Proyecto actualizado con éxito.");

                
            } 
            frmMain main = new frmMain();
            proyectos = GestionArchivos.leerProyectos();
            if(proyectos!=null){

                main.cargarProyectos();
            }
            dispose();
        } 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cboResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboResponsableActionPerformed
        Persona responsable = new Persona();
        
    }//GEN-LAST:event_cboResponsableActionPerformed

    boolean formularioValido(){
        boolean response = true;
        if(txtCodigo.getText().isBlank()) response = false;
        if(txtNombre.getText().isBlank()) response = false;
        if(Integer.parseInt(spinHorasEstimadas.getValue().toString())<1) response = false;
        if(txtFechaInicio.getText().isBlank()) response = false;
        if(txtFechaFin.getText().isBlank()) response = false;
        if(cboResponsable.getSelectedIndex()==0) response = false;
        if(cboEstado.getSelectedIndex()==0) response = false;
        
        return response;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProyecto(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<Persona> cboResponsable;
    private javax.swing.JCheckBox chckActivo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSlider sldAvance;
    private javax.swing.JSpinner spinHorasEstimadas;
    private javax.swing.JTextArea textAreaDescripcion;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtFechaCreacion;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
